version: 2.1
orbs:
  flutter: circleci/flutter@1.0.0

jobs:
  build-and-test:
    docker:
      - image: cirrusci/flutter:latest
    steps:
      - checkout
      - flutter/install
      - run:
          name: Get Dependencies
          command: flutter pub get
      - run:
          name: Run Tests
          command: flutter test

workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - build-and-test
